version: '3.8'

services:
  # PostgreSQL (configuración estándar)
  postgres:
    image: postgres:15
    container_name: postgres_todocompras
    restart: always
    ports:
      - "5432:5432"  # Expone PostgreSQL en localhost:5432
    environment:
      POSTGRES_DB: todoComprasDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: